service: serverless-concurrency-level1
frameworkVersion: '3'

plugins:
  - serverless-esbuild

provider:
  name: aws
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  profile: sandbox01
  runtime: nodejs16.x
  memorySize: 128
  timeout: 6

functions:
  recieve:
    handler: src/bootstrap.handle
    timeout: 10
    reservedConcurrency: 1
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
          batchSize: 1
resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "serverless-concurrency-level1"